profiles:
- name: default
  provider: github
  repos:
  - owner: cli
    name: cli
  authors:
    teams: []
    include: []
    exclude:
    - app/dependabot
  checks:
    hide_failing: false
  review_filter:
    enabled: true
  include_drafts: true
  poll_interval: 5m0s
- name: charm
  provider: github
  repos:
  - owner: charmbracelet
    name: bubbletea
  - owner: charmbracelet
    name: lipgloss
  authors:
    teams: []
    include: []
    exclude:
    - app/dependabot
  checks:
    hide_failing: true
  review_filter:
    enabled: false
  include_drafts: false
  poll_interval: 2m0s
